<a href="https://colab.research.google.com/github/keerthanaa-babu/EDA-sem-3/blob/main/EDA_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import pandas as pd
import numpy as np

In [80]:
df=pd.read_csv('/Suicide data.csv')

In [81]:
df.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [82]:
df.isnull().sum()

country                   0
year                      0
sex                       0
age                       0
suicides_no               0
population                0
suicides/100k pop         0
country-year              0
HDI for year          19456
 gdp_for_year ($)         0
gdp_per_capita ($)        0
generation                0
dtype: int64

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             27820 non-null  object
 1   year                27820 non-null  int64
 2   sex                 27820 non-null  object
 3   age                 27820 non-null  object
 4   suicides_no         27820 non-null  int64
 5   population          27820 non-null  int64
 6   suicides/100k pop   27820 non-null  float64
 7   country-year        27820 non-null  object
 8   HDI for year        8364 non-null   float64
 9    gdp_for_year ($)   27820 non-null  object
 10  gdp_per_capita ($)  27820 non-null  int64
 11  generation          27820 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 2.5+ MB

In [84]:
df.shape

(27820, 12)

In [85]:
df.columns

Index(['country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI for year',
       ' gdp_for_year ($) ', 'gdp_per_capita ($)', 'generation'],
      dtype='object')

In [86]:
df.dtypes

country                object
year                    int64
sex                    object
age                    object
suicides_no             int64
population              int64
suicides/100k pop     float64
country-year           object
HDI for year          float64
 gdp_for_year ($)      object
gdp_per_capita ($)      int64
generation             object
dtype: object

In [87]:
df.isnull().mean()*100

country                0.000000
year                   0.000000
sex                    0.000000
age                    0.000000
suicides_no            0.000000
population             0.000000
suicides/100k pop      0.000000
country-year           0.000000
HDI for year          69.935298
 gdp_for_year ($)      0.000000
gdp_per_capita ($)     0.000000
generation             0.000000
dtype: float64

In [88]:
df.describe()

,year,suicides_no,population,suicides/100k pop,HDI for year,gdp_per_capita ($)
count,27820.000000,27820.000000,2.782000e+04,27820.000000,8364.000000,27820.000000
mean,2001.258375,242.574407,1.844794e+06,12.816097,0.776601,16866.464414
std,8.469055,902.047917,3.911779e+06,18.961511,0.093367,18887.576472
min,1985.000000,0.000000,2.780000e+02,0.000000,0.483000,251.000000
25%,1995.000000,3.000000,9.749850e+04,0.920000,0.713000,3447.000000
50%,2002.000000,25.000000,4.301500e+05,5.990000,0.779000,9372.000000
75%,2008.000000,131.000000,1.486143e+06,16.620000,0.855000,24874.000000
max,2016.000000,22338.000000,4.380521e+07,224.970000,0.944000,126352.000000

In [89]:
df.describe(include='all')

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
count,27820,27820.000000,27820,27820,27820.000000,2.782000e+04,27820.000000,27820,8364.000000,27820,27820.000000,27820
unique,101,NaN,2,6,NaN,NaN,NaN,2321,NaN,2321,NaN,6
top,Austria,NaN,male,15-24 years,NaN,NaN,NaN,Uzbekistan2014,NaN,"63,067,077,179",NaN,Generation X
freq,382,NaN,13910,4642,NaN,NaN,NaN,12,NaN,12,NaN,6408
mean,NaN,2001.258375,NaN,NaN,242.574407,1.844794e+06,12.816097,NaN,0.776601,NaN,16866.464414,NaN
std,NaN,8.469055,NaN,NaN,902.047917,3.911779e+06,18.961511,NaN,0.093367,NaN,18887.576472,NaN
min,NaN,1985.000000,NaN,NaN,0.000000,2.780000e+02,0.000000,NaN,0.483000,NaN,251.000000,NaN
25%,NaN,1995.000000,NaN,NaN,3.000000,9.749850e+04,0.920000,NaN,0.713000,NaN,3447.000000,NaN
50%,NaN,2002.000000,NaN,NaN,25.000000,4.301500e+05,5.990000,NaN,0.779000,NaN,9372.000000,NaN
75%,NaN,2008.000000,NaN,NaN,131.000000,1.486143e+06,16.620000,NaN,0.855000,NaN,24874.000000,NaN
max,NaN,2016.000000,NaN,NaN,22338.000000,4.380521e+07,224.970000,NaN,0.944000,NaN,126352.000000,NaN

In [90]:
df.sample(5)

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
25632,Trinidad and Tobago,2011,female,55-74 years,4,105486,3.79,Trinidad and Tobago2011,0.767,"25,433,011,405",20557,Boomers
24911,Switzerland,2010,male,15-24 years,47,472649,9.94,Switzerland2010,0.924,"583,782,977,866",78474,Millenials
5862,Colombia,2003,female,5-14 years,48,4175544,1.15,Colombia2003,NaN,"94,684,584,163",2489,Millenials
13927,Kazakhstan,2005,female,5-14 years,24,1219019,1.97,Kazakhstan2005,0.746,"57,123,671,734",4096,Millenials
5241,Canada,2012,male,55-74 years,770,3586361,21.47,Canada2012,0.910,"1,824,288,757,448",55347,Boomers

In [91]:
df.notnull().sum()

country               27820
year                  27820
sex                   27820
age                   27820
suicides_no           27820
population            27820
suicides/100k pop     27820
country-year          27820
HDI for year           8364
 gdp_for_year ($)     27820
gdp_per_capita ($)    27820
generation            27820
dtype: int64

In [92]:
df.duplicated().sum()

np.int64(0)

In [93]:
df['country']

0           Albania
1           Albania
2           Albania
3           Albania
4           Albania
            ...
27815    Uzbekistan
27816    Uzbekistan
27817    Uzbekistan
27818    Uzbekistan
27819    Uzbekistan
Name: country, Length: 27820, dtype: object

In [94]:
df.mean(numeric_only=True)

year                  2.001258e+03
suicides_no           2.425744e+02
population            1.844794e+06
suicides/100k pop     1.281610e+01
HDI for year          7.766011e-01
gdp_per_capita ($)    1.686646e+04
dtype: float64

In [95]:
df.median(numeric_only=True)

year                    2002.000
suicides_no               25.000
population            430150.000
suicides/100k pop          5.990
HDI for year               0.779
gdp_per_capita ($)      9372.000
dtype: float64

In [96]:
df.mode()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Austria,2009.0,female,15-24 years,0.0,24000.0,0.0,Albania1987,0.713,"1,002,219,052,968",1299.0,Generation X
1,Iceland,NaN,male,25-34 years,NaN,NaN,NaN,Albania1988,0.772,"1,011,797,457,139",2303.0,NaN
2,Mauritius,NaN,NaN,35-54 years,NaN,NaN,NaN,Albania1989,0.888,"1,016,418,229",4104.0,NaN
3,Netherlands,NaN,NaN,55-74 years,NaN,NaN,NaN,Albania1992,NaN,"1,018,847,043,277",NaN,NaN
4,NaN,NaN,NaN,75+ years,NaN,NaN,NaN,Albania1993,NaN,"1,022,191,296",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2010,NaN,"99,698,453,261",NaN,NaN
2301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2011,NaN,"99,853,528,653",NaN,NaN
2302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2012,NaN,"99,886,577,331",NaN,NaN
2303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2013,NaN,"990,374,050",NaN,NaN
2304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Uzbekistan2014,NaN,"997,007,926",NaN,NaN

In [97]:
df.std(numeric_only=True)

year                  8.469055e+00
suicides_no           9.020479e+02
population            3.911779e+06
suicides/100k pop     1.896151e+01
HDI for year          9.336671e-02
gdp_per_capita ($)    1.888758e+04
dtype: float64

In [98]:
df.var(numeric_only=True)

year                  7.172489e+01
suicides_no           8.136904e+05
population            1.530202e+13
suicides/100k pop     3.595389e+02
HDI for year          8.717342e-03
gdp_per_capita ($)    3.567405e+08
dtype: float64

In [99]:
df.min(numeric_only=True)

year                  1985.000
suicides_no              0.000
population             278.000
suicides/100k pop        0.000
HDI for year             0.483
gdp_per_capita ($)     251.000
dtype: float64

In [100]:
df.max(numeric_only=True)

year                  2.016000e+03
suicides_no           2.233800e+04
population            4.380521e+07
suicides/100k pop     2.249700e+02
HDI for year          9.440000e-01
gdp_per_capita ($)    1.263520e+05
dtype: float64

In [101]:
df[['country','year']]

          country  year
0         Albania  1987
1         Albania  1987
2         Albania  1987
3         Albania  1987
4         Albania  1987
...           ...   ...
27815  Uzbekistan  2014
27816  Uzbekistan  2014
27817  Uzbekistan  2014
27818  Uzbekistan  2014
27819  Uzbekistan  2014

[27820 rows x 2 columns]

In [102]:
df.loc[10]

country                       Albania
year                             1987
sex                            female
age                       55-74 years
suicides_no                         0
population                     144600
suicides/100k pop                 0.0
country-year              Albania1987
HDI for year                      NaN
 gdp_for_year ($)       2,156,624,900
gdp_per_capita ($)                796
generation            G.I. Generation
Name: 10, dtype: object

In [103]:
df.iloc[10]

country                       Albania
year                             1987
sex                            female
age                       55-74 years
suicides_no                         0
population                     144600
suicides/100k pop                 0.0
country-year              Albania1987
HDI for year                      NaN
 gdp_for_year ($)       2,156,624,900
gdp_per_capita ($)                796
generation            G.I. Generation
Name: 10, dtype: object

In [104]:
df.iloc[5:15]

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent
7,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,NaN,"2,156,624,900",796,Boomers
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
9,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
10,Albania,1987,female,55-74 years,0,144600,0.00,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
11,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X
12,Albania,1988,female,75+ years,2,36400,5.49,Albania1988,NaN,"2,126,000,000",769,G.I. Generation
13,Albania,1988,male,15-24 years,17,319200,5.33,Albania1988,NaN,"2,126,000,000",769,Generation X
14,Albania,1988,male,75+ years,1,22300,4.48,Albania1988,NaN,"2,126,000,000",769,G.I. Generation

In [105]:
df[df['sex']=='male']

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
...,...,...,...,...,...,...,...,...,...,...,...,...
27809,Uzbekistan,2014,male,25-34 years,318,2739150,11.61,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27811,Uzbekistan,2014,male,55-74 years,144,1271111,11.33,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers
27812,Uzbekistan,2014,male,15-24 years,347,3126905,11.10,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27813,Uzbekistan,2014,male,75+ years,17,224995,7.56,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z

In [106]:
df[(df['year']>2000) & (df['sex']=='female')]

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
147,Albania,2001,female,75+ years,2,47254,4.23,Albania2001,NaN,"4,060,758,804",1451,Silent
149,Albania,2001,female,15-24 years,9,271359,3.32,Albania2001,NaN,"4,060,758,804",1451,Millenials
150,Albania,2001,female,35-54 years,12,370191,3.24,Albania2001,NaN,"4,060,758,804",1451,Boomers
152,Albania,2001,female,55-74 years,6,189799,3.16,Albania2001,NaN,"4,060,758,804",1451,Silent
154,Albania,2001,female,25-34 years,4,222771,1.80,Albania2001,NaN,"4,060,758,804",1451,Generation X
...,...,...,...,...,...,...,...,...,...,...,...,...
27814,Uzbekistan,2014,female,25-34 years,162,2735238,5.92,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [107]:
df.sort_values('suicides_no')

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
33,Albania,1989,female,5-14 years,0,321900,0.00,Albania1989,NaN,"2,335,124,988",833,Generation X
34,Albania,1989,female,75+ years,0,37000,0.00,Albania1989,NaN,"2,335,124,988",833,G.I. Generation
11684,Iceland,1985,female,75+ years,0,6100,0.00,Iceland1985,0.776,"2,939,845,038",13357,G.I. Generation
11685,Iceland,1985,male,5-14 years,0,21400,0.00,Iceland1985,0.776,"2,939,845,038",13357,Generation X
22315,Seychelles,2008,male,75+ years,0,1019,0.00,Seychelles2008,NaN,"967,199,594",11667,Silent
...,...,...,...,...,...,...,...,...,...,...,...,...
21057,Russian Federation,1999,male,35-54 years,20705,21016400,98.52,Russian Federation1999,NaN,"195,905,767,669",1412,Boomers
21068,Russian Federation,2000,male,35-54 years,21063,21378098,98.53,Russian Federation2000,NaN,"259,708,496,267",1879,Boomers
21080,Russian Federation,2001,male,35-54 years,21262,21476420,99.00,Russian Federation2001,NaN,"306,602,673,980",2229,Boomers
21008,Russian Federation,1995,male,35-54 years,21706,19249600,112.76,Russian Federation1995,NaN,"395,531,066,563",2844,Boomers
20996,Russian Federation,1994,male,35-54 years,22338,19044200,117.30,Russian Federation1994,NaN,"395,077,301,248",2853,Boomers

In [108]:
df.sort_values('suicides_no',ascending=False)

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
20996,Russian Federation,1994,male,35-54 years,22338,19044200,117.30,Russian Federation1994,NaN,"395,077,301,248",2853,Boomers
21008,Russian Federation,1995,male,35-54 years,21706,19249600,112.76,Russian Federation1995,NaN,"395,531,066,563",2844,Boomers
21080,Russian Federation,2001,male,35-54 years,21262,21476420,99.00,Russian Federation2001,NaN,"306,602,673,980",2229,Boomers
21068,Russian Federation,2000,male,35-54 years,21063,21378098,98.53,Russian Federation2000,NaN,"259,708,496,267",1879,Boomers
21057,Russian Federation,1999,male,35-54 years,20705,21016400,98.52,Russian Federation1999,NaN,"195,905,767,669",1412,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
11169,Guyana,1996,female,5-14 years,0,85353,0.00,Guyana1996,NaN,"705,406,001",1070,Millenials
11135,Guyana,1993,male,75+ years,0,4112,0.00,Guyana1993,NaN,"442,273,433",671,G.I. Generation
11134,Guyana,1993,male,5-14 years,0,88194,0.00,Guyana1993,NaN,"442,273,433",671,Millenials
11133,Guyana,1993,female,75+ years,0,5036,0.00,Guyana1993,NaN,"442,273,433",671,G.I. Generation
11,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,NaN,"2,156,624,900",796,Generation X

In [109]:
df.sort_values(['country','year'])

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [110]:
df['Suicide Rate']=(df['suicides_no']/df['population'])*100000

In [111]:
df.rename(columns={'Suicide Rate':'Suicide_Rate'},inplace=True)

In [112]:
df['GDP Category']=df['gdp_per_capita ($)'].apply(lambda x:'High' if x>20000 else 'Low')

In [113]:
df['sex'].replace({'male':'M','female':'F'})

0        M
1        M
2        F
3        M
4        M
        ..
27815    F
27816    F
27817    M
27818    F
27819    F
Name: sex, Length: 27820, dtype: object

In [114]:
df['country'].value_counts()

country
Austria                   382
Mauritius                 382
Netherlands               382
Iceland                   382
Brazil                    372
                         ...
Bosnia and Herzegovina     24
Dominica                   12
Cabo Verde                 12
Macau                      12
Mongolia                   10
Name: count, Length: 101, dtype: int64

In [115]:
df['country'].unique()

array(['Albania', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Barbados', 'Belarus', 'Belgium', 'Belize',
       'Bosnia and Herzegovina', 'Brazil', 'Bulgaria', 'Cabo Verde',
       'Canada', 'Chile', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic', 'Denmark', 'Dominica', 'Ecuador',
       'El Salvador', 'Estonia', 'Fiji', 'Finland', 'France', 'Georgia',
       'Germany', 'Greece', 'Grenada', 'Guatemala', 'Guyana', 'Hungary',
       'Iceland', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Kazakhstan', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Latvia',
       'Lithuania', 'Luxembourg', 'Macau', 'Maldives', 'Malta',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Norway', 'Oman', 'Panama', 'Paraguay',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Romania', 'Russian Federation',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and Grenadines', 'San Marino', 'Serbia',
       'Seychelles', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa',
       'Spain', 'Sri Lanka', 'Suriname', 'Sweden', 'Switzerland',
       'Thailand', 'Trinidad and Tobago', 'Turkey', 'Turkmenistan',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan'], dtype=object)

In [116]:
df['country'].nunique()

101

In [117]:
df.groupby('country')['suicides_no'].sum()

country
Albania                    1970
Antigua and Barbuda          11
Argentina                 82219
Armenia                    1905
Aruba                       101
                         ...
United Arab Emirates        622
United Kingdom           136805
United States           1034013
Uruguay                   13138
Uzbekistan                34803
Name: suicides_no, Length: 101, dtype: int64

In [118]:
pd.pivot_table(df,values='suicides_no',index='country',columns='sex',aggfunc='sum')

sex                   female    male
country
Albania                  693    1277
Antigua and Barbuda        1      10
Argentina              18326   63893
Armenia                  495    1410
Aruba                     17      84
...                      ...     ...
United Arab Emirates      98     524
United Kingdom         32687  104118
United States         213797  820216
Uruguay                 2820   10318
Uzbekistan              9260   25543

[101 rows x 2 columns]

In [119]:
df1=df.iloc[:5000]
df2=df.iloc[5000:]
new_df=pd.concat([df1,df2])

In [120]:
multi=df.set_index(['country','year'])
multi.stack()

country     year
Albania     1987  sex                             male
                  age                      15-24 years
                  suicides_no                       21
                  population                    312900
                  suicides/100k pop               6.71
                                             ...
Uzbekistan  2014   gdp_for_year ($)     63,067,077,179
                  gdp_per_capita ($)              2309
                  generation                   Boomers
                  Suicide_Rate                1.459413
                  GDP Category                     Low
Length: 314384, dtype: object

In [121]:
multi.reset_index()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation,Suicide_Rate,GDP Category
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X,6.711409,Low
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent,5.194805,Low
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X,4.832585,Low
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,4.587156,Low
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers,3.281079,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X,2.955121,Low
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent,2.582756,Low
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z,2.172215,Low
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z,1.671987,Low
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers,1.459413,Low

In [122]:
df.set_index('country')

,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation,Suicide_Rate,GDP Category
country,,,,,,,,,,,,,
Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X,6.711409,Low
Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent,5.194805,Low
Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X,4.832585,Low
Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,4.587156,Low
Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers,3.281079,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X,2.955121,Low
Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent,2.582756,Low
Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z,2.172215,Low
Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z,1.671987,Low
Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers,1.459413,Low

In [123]:
df['suicides_no'].rank(ascending=False)

0        14503.0
1        15555.5
2        16019.5
3        22770.0
4        17362.0
          ...
27815     7770.0
27816    17362.0
27817    10354.0
27818    11606.0
27819    14503.0
Name: suicides_no, Length: 27820, dtype: float64

In [124]:
df.nlargest(10,'suicides_no')

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation,Suicide_Rate,GDP Category
20996,Russian Federation,1994,male,35-54 years,22338,19044200,117.30,Russian Federation1994,NaN,"395,077,301,248",2853,Boomers,117.295555,Low
21008,Russian Federation,1995,male,35-54 years,21706,19249600,112.76,Russian Federation1995,NaN,"395,531,066,563",2844,Boomers,112.760785,Low
21080,Russian Federation,2001,male,35-54 years,21262,21476420,99.00,Russian Federation2001,NaN,"306,602,673,980",2229,Boomers,99.001603,Low
21068,Russian Federation,2000,male,35-54 years,21063,21378098,98.53,Russian Federation2000,NaN,"259,708,496,267",1879,Boomers,98.526071,Low
21057,Russian Federation,1999,male,35-54 years,20705,21016400,98.52,Russian Federation1999,NaN,"195,905,767,669",1412,Boomers,98.518300,Low
21020,Russian Federation,1996,male,35-54 years,20562,19507100,105.41,Russian Federation1996,NaN,"391,719,993,757",2813,Boomers,105.407775,Low
20984,Russian Federation,1993,male,35-54 years,20256,18908000,107.13,Russian Federation1993,NaN,"435,083,713,851",3160,Boomers,107.129257,Low
21092,Russian Federation,2002,male,35-54 years,20119,21320535,94.36,Russian Federation2002,NaN,"345,110,438,692",2527,Boomers,94.364424,Low
21033,Russian Federation,1997,male,35-54 years,18973,19913400,95.28,Russian Federation1997,NaN,"404,926,534,140",2907,Boomers,95.277552,Low
21105,Russian Federation,2003,male,35-54 years,18681,21007346,88.93,Russian Federation2003,NaN,"430,347,770,732",3141,Boomers,88.926036,Low

In [125]:
df.nsmallest(10,'suicides_no')

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation,Suicide_Rate,GDP Category
9,Albania,1987,female,5-14 years,0,311000,0.0,Albania1987,NaN,"2,156,624,900",796,Generation X,0.0,Low
10,Albania,1987,female,55-74 years,0,144600,0.0,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,0.0,Low
11,Albania,1987,male,5-14 years,0,338200,0.0,Albania1987,NaN,"2,156,624,900",796,Generation X,0.0,Low
22,Albania,1988,female,5-14 years,0,317200,0.0,Albania1988,NaN,"2,126,000,000",769,Generation X,0.0,Low
23,Albania,1988,male,5-14 years,0,345000,0.0,Albania1988,NaN,"2,126,000,000",769,Generation X,0.0,Low
33,Albania,1989,female,5-14 years,0,321900,0.0,Albania1989,NaN,"2,335,124,988",833,Generation X,0.0,Low
34,Albania,1989,female,75+ years,0,37000,0.0,Albania1989,NaN,"2,335,124,988",833,G.I. Generation,0.0,Low
35,Albania,1989,male,5-14 years,0,349700,0.0,Albania1989,NaN,"2,335,124,988",833,Generation X,0.0,Low
44,Albania,1992,female,5-14 years,0,336700,0.0,Albania1992,NaN,"709,452,584",251,Millenials,0.0,Low
45,Albania,1992,female,75+ years,0,38700,0.0,Albania1992,NaN,"709,452,584",251,G.I. Generation,0.0,Low

In [126]:
df.memory_usage()

Index                    132
country               222560
year                  222560
sex                   222560
age                   222560
suicides_no           222560
population            222560
suicides/100k pop     222560
country-year          222560
HDI for year          222560
 gdp_for_year ($)     222560
gdp_per_capita ($)    222560
generation            222560
Suicide_Rate          222560
GDP Category          222560
dtype: int64

In [127]:
df.to_csv("processed_suicide_data.csv",index=False)

In [128]:
df.drop('country-year',axis=1)

,country,year,sex,age,suicides_no,population,suicides/100k pop,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation,Suicide_Rate,GDP Category
0,Albania,1987,male,15-24 years,21,312900,6.71,NaN,"2,156,624,900",796,Generation X,6.711409,Low
1,Albania,1987,male,35-54 years,16,308000,5.19,NaN,"2,156,624,900",796,Silent,5.194805,Low
2,Albania,1987,female,15-24 years,14,289700,4.83,NaN,"2,156,624,900",796,Generation X,4.832585,Low
3,Albania,1987,male,75+ years,1,21800,4.59,NaN,"2,156,624,900",796,G.I. Generation,4.587156,Low
4,Albania,1987,male,25-34 years,9,274300,3.28,NaN,"2,156,624,900",796,Boomers,3.281079,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,0.675,"63,067,077,179",2309,Generation X,2.955121,Low
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,0.675,"63,067,077,179",2309,Silent,2.582756,Low
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,0.675,"63,067,077,179",2309,Generation Z,2.172215,Low
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,0.675,"63,067,077,179",2309,Generation Z,1.671987,Low
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,0.675,"63,067,077,179",2309,Boomers,1.459413,Low

In [129]:
df.drop(columns=['country-year'])

,country,year,sex,age,suicides_no,population,suicides/100k pop,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation,Suicide_Rate,GDP Category
0,Albania,1987,male,15-24 years,21,312900,6.71,NaN,"2,156,624,900",796,Generation X,6.711409,Low
1,Albania,1987,male,35-54 years,16,308000,5.19,NaN,"2,156,624,900",796,Silent,5.194805,Low
2,Albania,1987,female,15-24 years,14,289700,4.83,NaN,"2,156,624,900",796,Generation X,4.832585,Low
3,Albania,1987,male,75+ years,1,21800,4.59,NaN,"2,156,624,900",796,G.I. Generation,4.587156,Low
4,Albania,1987,male,25-34 years,9,274300,3.28,NaN,"2,156,624,900",796,Boomers,3.281079,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,0.675,"63,067,077,179",2309,Generation X,2.955121,Low
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,0.675,"63,067,077,179",2309,Silent,2.582756,Low
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,0.675,"63,067,077,179",2309,Generation Z,2.172215,Low
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,0.675,"63,067,077,179",2309,Generation Z,1.671987,Low
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,0.675,"63,067,077,179",2309,Boomers,1.459413,Low